/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginSystem;

import Enumerations.*;
import Objects.Council;
import Objects.Shirt;
import Objects.Student;
import java.awt.Component;
import javax.swing.JTextField;

/**
 *
 * @author violet
 */
public class RegistrationInterface extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public RegistrationInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIDNumber = new javax.swing.JLabel();
        labelFirstName = new javax.swing.JLabel();
        labelShirtSize = new javax.swing.JLabel();
        labelDepartment = new javax.swing.JLabel();
        labelYear = new javax.swing.JLabel();
        labelInterest = new javax.swing.JLabel();
        labelPayment = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelContact = new javax.swing.JLabel();
        actionRegister = new javax.swing.JButton();
        actionCancel = new javax.swing.JButton();
        firstName = new javax.swing.JTextField();
        payment = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        department = new javax.swing.JComboBox();
        shirtSize = new javax.swing.JComboBox();
        labelHeader = new javax.swing.JLabel();
        yearLevel = new javax.swing.JComboBox();
        interestScroller = new javax.swing.JScrollPane();
        interests = new javax.swing.JTextArea();
        idNumber = new javax.swing.JFormattedTextField();
        headerSeparator = new javax.swing.JSeparator();
        customSize = new javax.swing.JTextField();
        labelCustomSize = new javax.swing.JLabel();
        tipInterest = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox();
        labelPassword = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        labelLastName = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelIDNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelIDNumber.setText("ID Number");

        labelFirstName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelFirstName.setText("First Name");

        labelShirtSize.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelShirtSize.setText("Shirtsize");

        labelDepartment.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelDepartment.setText("Department");

        labelYear.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelYear.setText("Year");

        labelInterest.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelInterest.setText("Interest");

        labelPayment.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelPayment.setText("Payment");

        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelEmail.setText("Email");

        labelContact.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelContact.setText("Contact");

        actionRegister.setText("Register");
        actionRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionRegisterActionPerformed(evt);
            }
        });

        actionCancel.setText("Cancel");
        actionCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionCancelActionPerformed(evt);
            }
        });

        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });

        payment.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        payment.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });

        for(Department d : Department.values()) {
            department.addItem(d);
        }
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });

        for(ShirtSize s : ShirtSize.values()) {
            shirtSize.addItem(s);
        }
        shirtSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shirtSizeActionPerformed(evt);
            }
        });

        labelHeader.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        labelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeader.setText("Register Student");

        for(YearLevel y: YearLevel.values()) {
            yearLevel.addItem(y);
        }

        interests.setColumns(20);
        interests.setLineWrap(true);
        interests.setRows(5);
        interests.setWrapStyleWord(true);
        interestScroller.setViewportView(interests);

        try {
            idNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        idNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelCustomSize.setText("Custom Size:");

        tipInterest.setText("One(1) interest per line");

        labelGender.setText("Gender");

        for(Gender g : Gender.values()) {
            gender.addItem(g);
        }

        labelPassword.setText("Password");

        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelLastName.setText("Last Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelShirtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shirtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCustomSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customSize))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(payment)
                                .addGap(24, 24, 24)
                                .addComponent(actionRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(actionCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelContact)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(interestScroller, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerSeparator)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelIDNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(labelFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelDepartment, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(firstName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelLastName)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password)
                                    .addComponent(lastName, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelYear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearLevel, 0, 126, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelGender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIDNumber)
                    .addComponent(idNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFirstName)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLastName)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDepartment)
                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelYear)
                    .addComponent(yearLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGender)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shirtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelShirtSize)
                    .addComponent(customSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCustomSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelInterest)
                    .addComponent(interestScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(tipInterest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContact)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPayment)
                    .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void actionCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_actionCancelActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed

    }//GEN-LAST:event_firstNameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed

    }//GEN-LAST:event_emailActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void actionRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionRegisterActionPerformed
        Student student = new Student();
        student.setId(Long.parseLong(idNumber.getText()));
        student.setFirstName(firstName.getText());
        student.setLastName(firstName.getText());
        student.setDepartment(Department.values()[department.getSelectedIndex()]);
        student.setGender(Gender.values()[department.getSelectedIndex()]);
        student.setYearLevel(YearLevel.values()[yearLevel.getSelectedIndex()]);
        Shirt shirt = new Shirt();
        shirt.setClaimed(false);
        shirt.setShirtSize(
                customSize.isEnabled() ? customSize.getText()
                        : shirtSize.getSelectedItem().toString()
        );
        student.setShirt(shirt);
        student.setInterest(interests.getText());
        student.setEmail(email.getText());
        student.setContact(contact.getText());
        student.setPayment(Double.parseDouble(payment.getText()));

        if (godAccountActive) {
            Council council = new Council();
            council.setId(Long.parseLong(idNumber.getText()));
            council.setFirstName(firstName.getText());
            council.setLastName(firstName.getText());
            council.setPassword(password.getPassword().toString());
            council.setDepartment(Department.values()[department.getSelectedIndex()]);
            council.setGender(Gender.values()[department.getSelectedIndex()]);
            council.setYearLevel(YearLevel.values()[yearLevel.getSelectedIndex()]);
            Shirt shirt2 = new Shirt();
            shirt2.setClaimed(false);
            shirt2.setShirtSize(
                    customSize.isEnabled() ? customSize.getText()
                            : shirtSize.getSelectedItem().toString()
            );
            council.setShirt(shirt2);
            council.setInterest(interests.getText());
            council.setEmail(email.getText());
            council.setContact(contact.getText());
            council.setPayment(Double.parseDouble(payment.getText()));
        }

    }//GEN-LAST:event_actionRegisterActionPerformed

    private void shirtSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shirtSizeActionPerformed
        customSize.setVisible(shirtSize.getSelectedIndex() == ShirtSize.values().length - 1);
        labelCustomSize.setVisible(shirtSize.getSelectedIndex() == ShirtSize.values().length - 1);
        revalidate();
        repaint();
    }//GEN-LAST:event_shirtSizeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        labelPassword.setVisible(godAccountActive);
        password.setVisible(godAccountActive);

        customSize.setVisible(false);
        labelCustomSize.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationInterface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationInterface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationInterface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationInterface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationInterface().setVisible(true);
            }
        });
    }

    public void activateGodAccount() {
        godAccountActive = true;
    }

    private boolean godAccountActive = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionCancel;
    private javax.swing.JButton actionRegister;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField customSize;
    private javax.swing.JComboBox department;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstName;
    private javax.swing.JComboBox gender;
    private javax.swing.JSeparator headerSeparator;
    private javax.swing.JFormattedTextField idNumber;
    private javax.swing.JScrollPane interestScroller;
    private javax.swing.JTextArea interests;
    private javax.swing.JLabel labelContact;
    private javax.swing.JLabel labelCustomSize;
    private javax.swing.JLabel labelDepartment;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelIDNumber;
    private javax.swing.JLabel labelInterest;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPayment;
    private javax.swing.JLabel labelShirtSize;
    private javax.swing.JLabel labelYear;
    private javax.swing.JTextField lastName;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField payment;
    private javax.swing.JComboBox shirtSize;
    private javax.swing.JLabel tipInterest;
    private javax.swing.JComboBox yearLevel;
    // End of variables declaration//GEN-END:variables
}
