/*
 *  ==++++++++++++++++++++++++++++++++++++++++++++++++++++==
 *  |      CENTRAL PHILIPPINE UNIVERSITY                   |
 *  |      Bachelor of Science in Software Engineering     |
 *  |      Jaro, Iloilo City, Philippines                  |
 *  |                                                      |
 *  |          This program is written by Rave, ©2014.     |
 *  |          You are free to use and distribute this.    |
 *  |          Reach me at: admin@blackout.biz.tm          |
 *  |                                                      |
 *  |               ~~~"CODE the FUTURE"~~~                |
 *  ==++++++++++++++++++++++++++++++++++++++++++++++++++++==
 */
package com.infinitech.gui.main;

import com.infinitech.enumerations.Department;
import com.infinitech.enumerations.Gender;
import com.infinitech.enumerations.LogType;
import com.infinitech.enumerations.YearLevel;
import com.infinitech.gui.loginsystem.LoginInterface;
import com.infinitech.gui.loginsystem.RegistrationInterface;
import com.infinitech.gui.tools.EventInterface;
import com.infinitech.gui.tools.LogInterface;
import com.infinitech.gui.tools.NukeConfirmInterface;
import com.infinitech.objects.Council;
import com.infinitech.objects.Event;
import com.infinitech.objects.Log;
import com.infinitech.objects.Student;
import java.util.Date;
import java.util.List;
import javax.persistence.NoResultException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rave Noren Gidor-Sambo Villavicencio-Arevalo
 */
public class Dashboard extends javax.swing.JFrame {

    private static final FundsInterface fundInterface = new FundsInterface();

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        dashboardTab = new javax.swing.JPanel();
        coucilDetailPane = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        infoName = new javax.swing.JTextField();
        labelDepartment = new javax.swing.JLabel();
        infoDepartment = new javax.swing.JTextField();
        labelYearLevel = new javax.swing.JLabel();
        infoYearLevel = new javax.swing.JTextField();
        actionsPane = new javax.swing.JPanel();
        registerNewStudent = new javax.swing.JButton();
        registerNewCouncil = new javax.swing.JButton();
        borrowEquipment = new javax.swing.JButton();
        viewEquipment = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        fundButton = new javax.swing.JButton();
        announcementPane = new javax.swing.JPanel();
        announcementScroller = new javax.swing.JScrollPane();
        announcement = new javax.swing.JTextArea();
        logout = new javax.swing.JButton();
        events = new javax.swing.JPanel();
        filterEventPane = new javax.swing.JPanel();
        labelEvent = new javax.swing.JLabel();
        eventsSelection = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        searchStudentPanel = new javax.swing.JPanel();
        studentDetailsPane = new javax.swing.JPanel();
        labelIDNumber = new javax.swing.JLabel();
        idNumber = new javax.swing.JTextField();
        labelFirstName = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        labelLastName = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        departmentLabel = new javax.swing.JLabel();
        department = new javax.swing.JComboBox();
        labelYear = new javax.swing.JLabel();
        year = new javax.swing.JComboBox();
        labelGender = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox();
        labelShirtSize = new javax.swing.JLabel();
        shirtSize = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        labelContactNumber = new javax.swing.JLabel();
        contactNumber = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        spacer = new javax.swing.JLabel();
        actionUpdate = new javax.swing.JButton();
        labelSearchKeyword = new javax.swing.JLabel();
        passwordsPane = new javax.swing.JPanel();
        labelOldPassword = new javax.swing.JLabel();
        oldPassword = new javax.swing.JTextField();
        labelNewPassword = new javax.swing.JLabel();
        newPassword = new javax.swing.JTextField();
        labelConfirmPassword = new javax.swing.JLabel();
        confirmPassword = new javax.swing.JTextField();
        actionChangePassword = new javax.swing.JButton();
        actionSearch = new javax.swing.JButton();
        keyword = new javax.swing.JFormattedTextField();
        tools = new javax.swing.JMenuBar();
        showLog = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        coucilDetailPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Council"));
        coucilDetailPane.setLayout(new java.awt.GridLayout(0, 1));

        labelName.setText("Name");
        coucilDetailPane.add(labelName);
        coucilDetailPane.add(infoName);

        labelDepartment.setText("Department");
        coucilDetailPane.add(labelDepartment);
        coucilDetailPane.add(infoDepartment);

        labelYearLevel.setText("Year Level");
        coucilDetailPane.add(labelYearLevel);
        coucilDetailPane.add(infoYearLevel);

        actionsPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        actionsPane.setLayout(new java.awt.GridLayout(0, 2));

        registerNewStudent.setText("Register New Student");
        registerNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerNewStudentActionPerformed(evt);
            }
        });
        actionsPane.add(registerNewStudent);

        registerNewCouncil.setText("Register New Council Member");
        registerNewCouncil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerNewCouncilActionPerformed(evt);
            }
        });
        actionsPane.add(registerNewCouncil);

        borrowEquipment.setText("Borrow/Return an Equipment");
        borrowEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowEquipmentActionPerformed(evt);
            }
        });
        actionsPane.add(borrowEquipment);

        viewEquipment.setText("Show Unreturned Equipments");
        viewEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEquipmentActionPerformed(evt);
            }
        });
        actionsPane.add(viewEquipment);

        jButton1.setText("View Students with Registered Shirtsizes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        actionsPane.add(jButton1);

        fundButton.setText("Funds");
        fundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundButtonActionPerformed(evt);
            }
        });
        actionsPane.add(fundButton);

        announcementPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Announcements"));

        announcement.setColumns(20);
        announcement.setRows(5);
        announcementScroller.setViewportView(announcement);

        javax.swing.GroupLayout announcementPaneLayout = new javax.swing.GroupLayout(announcementPane);
        announcementPane.setLayout(announcementPaneLayout);
        announcementPaneLayout.setHorizontalGroup(
            announcementPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(announcementScroller)
                .addContainerGap())
        );
        announcementPaneLayout.setVerticalGroup(
            announcementPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(announcementScroller)
        );

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboardTabLayout = new javax.swing.GroupLayout(dashboardTab);
        dashboardTab.setLayout(dashboardTabLayout);
        dashboardTabLayout.setHorizontalGroup(
            dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardTabLayout.createSequentialGroup()
                        .addComponent(coucilDetailPane, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(announcementPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(actionsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dashboardTabLayout.setVerticalGroup(
            dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(coucilDetailPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(announcementPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionsPane, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Dashboard", dashboardTab);

        labelEvent.setText("Event");
        filterEventPane.add(labelEvent);

        eventsSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsSelectionActionPerformed(evt);
            }
        });
        filterEventPane.add(eventsSelection);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Contact Number", "Year", "Interest"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(3).setMinWidth(80);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel1.setText("Potential Representatives");

        javax.swing.GroupLayout eventsLayout = new javax.swing.GroupLayout(events);
        events.setLayout(eventsLayout);
        eventsLayout.setHorizontalGroup(
            eventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                    .addGroup(eventsLayout.createSequentialGroup()
                        .addGroup(eventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filterEventPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        eventsLayout.setVerticalGroup(
            eventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filterEventPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Events", events);

        studentDetailsPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        studentDetailsPane.setLayout(new java.awt.GridLayout(0, 2));

        labelIDNumber.setText("ID Number");
        studentDetailsPane.add(labelIDNumber);

        idNumber.setEditable(false);
        studentDetailsPane.add(idNumber);

        labelFirstName.setText("First Name");
        studentDetailsPane.add(labelFirstName);

        firstName.setEditable(false);
        studentDetailsPane.add(firstName);

        labelLastName.setText("Last Name");
        studentDetailsPane.add(labelLastName);

        lastName.setEditable(false);
        studentDetailsPane.add(lastName);

        departmentLabel.setText("Department");
        studentDetailsPane.add(departmentLabel);

        studentDetailsPane.add(department);

        labelYear.setText("Year");
        studentDetailsPane.add(labelYear);

        studentDetailsPane.add(year);

        labelGender.setText("Gender");
        studentDetailsPane.add(labelGender);

        studentDetailsPane.add(gender);

        labelShirtSize.setText("Shirt Size");
        studentDetailsPane.add(labelShirtSize);
        studentDetailsPane.add(shirtSize);

        labelEmail.setText("Email");
        studentDetailsPane.add(labelEmail);
        studentDetailsPane.add(email);

        labelContactNumber.setText("Contact Number");
        studentDetailsPane.add(labelContactNumber);
        studentDetailsPane.add(contactNumber);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        studentDetailsPane.add(jPanel1);

        jCheckBox1.setText("Coordinator");
        studentDetailsPane.add(jCheckBox1);
        studentDetailsPane.add(spacer);

        actionUpdate.setText("Update");
        actionUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionUpdateActionPerformed(evt);
            }
        });
        studentDetailsPane.add(actionUpdate);

        labelSearchKeyword.setText("ID Number");

        passwordsPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelOldPassword.setText("Old Password");

        labelNewPassword.setText("New Password");

        labelConfirmPassword.setText("Confirm Password");

        actionChangePassword.setText("Change Password");

        javax.swing.GroupLayout passwordsPaneLayout = new javax.swing.GroupLayout(passwordsPane);
        passwordsPane.setLayout(passwordsPaneLayout);
        passwordsPaneLayout.setHorizontalGroup(
            passwordsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordsPaneLayout.createSequentialGroup()
                        .addGroup(passwordsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(passwordsPaneLayout.createSequentialGroup()
                                .addGroup(passwordsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(passwordsPaneLayout.createSequentialGroup()
                                .addComponent(labelOldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24)))
                        .addGroup(passwordsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(oldPassword)
                            .addComponent(newPassword)
                            .addComponent(confirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordsPaneLayout.createSequentialGroup()
                        .addGap(0, 157, Short.MAX_VALUE)
                        .addComponent(actionChangePassword)))
                .addContainerGap())
        );
        passwordsPaneLayout.setVerticalGroup(
            passwordsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordsPaneLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(passwordsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOldPassword)
                    .addComponent(oldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(passwordsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNewPassword)
                    .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(passwordsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConfirmPassword)
                    .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionChangePassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        actionSearch.setText("Search");
        actionSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionSearchActionPerformed(evt);
            }
        });

        try {
            keyword.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout searchStudentPanelLayout = new javax.swing.GroupLayout(searchStudentPanel);
        searchStudentPanel.setLayout(searchStudentPanelLayout);
        searchStudentPanelLayout.setHorizontalGroup(
            searchStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(searchStudentPanelLayout.createSequentialGroup()
                        .addComponent(labelSearchKeyword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keyword))
                    .addComponent(studentDetailsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchStudentPanelLayout.createSequentialGroup()
                        .addComponent(actionSearch)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchStudentPanelLayout.setVerticalGroup(
            searchStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSearchKeyword)
                    .addComponent(actionSearch)
                    .addComponent(keyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentDetailsPane, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addGroup(searchStudentPanelLayout.createSequentialGroup()
                        .addComponent(passwordsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabs.addTab("Search/Edit Student Information", searchStudentPanel);

        showLog.setText("Tools");

        jMenuItem1.setText("Show Logs");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        showLog.add(jMenuItem1);

        jMenuItem2.setText("Customize Events");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        showLog.add(jMenuItem2);

        jMenuItem3.setText("Add Equipment");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        showLog.add(jMenuItem3);

        tools.add(showLog);

        jMenu1.setText("Nuke");

        jMenuItem4.setForeground(new java.awt.Color(255, 0, 51));
        jMenuItem4.setText("(WARNING) Nuke Database");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        tools.add(jMenu1);

        setJMenuBar(tools);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        infoName.setText("     " + getCouncil().getFirstName() + " " + getCouncil().getLastName());
        infoDepartment.setText("     " + getCouncil().getDepartment().toString());
        infoYearLevel.setText("     " + getCouncil().getYearLevel().toString());

        List<Event> evts = Event.getFinder().findAll();
        for (Event e : evts) {
            eventsSelection.addItem(e.getEventName());
        }

        eventsSelection.setSelectedIndex(0);
        passwordsPane.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        LogInterface logInterface = new LogInterface();
        logInterface.setCouncil(council);
        logInterface.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void registerNewCouncilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerNewCouncilActionPerformed
        RegistrationInterface registrationInterface = new RegistrationInterface();
        registrationInterface.activateCouncilRegistration();
        registrationInterface.setVisible(true);
    }//GEN-LAST:event_registerNewCouncilActionPerformed

    private void registerNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerNewStudentActionPerformed
        RegistrationInterface registrationInterface = new RegistrationInterface();
        registrationInterface.setCouncil(getCouncil());
        registrationInterface.setVisible(true);
    }//GEN-LAST:event_registerNewStudentActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        logout();
    }//GEN-LAST:event_logoutActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        logout();
    }//GEN-LAST:event_formWindowClosed

    private void eventsSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsSelectionActionPerformed

        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Student ID", "Student Name", "Contact Number", "Year", "Interest"
                }
        ));

        jScrollPane1.setViewportView(jTable1);

        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(3).setMinWidth(80);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        Event event = Event.getFinder().findRecordByField("eventName", (String) eventsSelection.getSelectedItem());
        List<Student> reps = event.getStudents();

        for (Student rep : reps) {
            String data1 = String.valueOf(rep.getId());
            String data2 = rep.getFirstName() + " " + rep.getLastName();
            String data3 = rep.getContact();
            String data4 = rep.getYearLevel().toString();
            String data5 = rep.getInterest().replaceAll("\n", ",");

            String[] data = {data1, data2, data3, data4, data5};
            dtm.addRow(data);
        }

    }//GEN-LAST:event_eventsSelectionActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        EventInterface eventInterface = new EventInterface();
        eventInterface.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void borrowEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowEquipmentActionPerformed
        BorrowEquipmentInterface borrowEquipmentInterface = new BorrowEquipmentInterface();
        borrowEquipmentInterface.setVisible(true);
    }//GEN-LAST:event_borrowEquipmentActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AddEquipmentInterface addEquipmentInterface = new AddEquipmentInterface();
        addEquipmentInterface.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ShirtInterface shirtInterface = new ShirtInterface();
        shirtInterface.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        NukeConfirmInterface nukeConfirmInterface = new NukeConfirmInterface();
        nukeConfirmInterface.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void viewEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEquipmentActionPerformed
        UnreturnedEquipmentsInterface unreturnedEquipmentsInterface = new UnreturnedEquipmentsInterface();
        unreturnedEquipmentsInterface.setVisible(true);
    }//GEN-LAST:event_viewEquipmentActionPerformed

    private void actionSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionSearchActionPerformed
        try {
            student = Student.getStudentFinder()
                    .findRecordById(Long.parseLong(keyword.getText().replaceAll("-", "")));
        } catch (NoResultException e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Student with ID number " + keyword.getText() + " does not exist!",
                    "Does not exist",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        idNumber.setText("" + student.getId());
        firstName.setText(student.getFirstName());
        lastName.setText(student.getLastName());
        department.setSelectedItem(student.getDepartment());
        year.setSelectedItem(student.getYearLevel());
        gender.setSelectedItem(student.getGender());
        shirtSize.setText(student.getShirt().getShirtSize());
        email.setText(student.getEmail());
        contactNumber.setText(student.getContact());

        if (student instanceof Council) {
            passwordsPane.setVisible(true);
        }
    }//GEN-LAST:event_actionSearchActionPerformed

    private void fundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundButtonActionPerformed
        // TODO add your handling code here:
        String idString = JOptionPane.showInputDialog("ID Number:");
        long idSearch = Long.parseLong(idString);
        Student studentSearch = Student.getStudentFinder().findRecordById(idSearch);
        if (studentSearch.isCoordinator()) {
            fundInterface.setVisible(true);
        } else {
            fundInterface.dispose();
        }
    }//GEN-LAST:event_fundButtonActionPerformed

    private void actionUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionUpdateActionPerformed
        student.setDepartment(Department.values()[department.getSelectedIndex()]);
        student.setYearLevel(YearLevel.values()[year.getSelectedIndex()]);
        student.setGender(Gender.values()[gender.getSelectedIndex()]);
        student.getShirt().setShirtSize(shirtSize.getText());
        student.update();
    }//GEN-LAST:event_actionUpdateActionPerformed

    public void logout() {
        Log log = new Log();
        log.setLogType(LogType.LOGOUT);
        log.setLogDate(new Date());
        log.setDescription(council.getFirstName() + " has logged out.");
        council.getLogs().add(log);
        council.update();
        this.dispose();
        new LoginInterface().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    public static Council getCouncil() {
        return council;
    }

    public void setCouncil(Council council) {
        Dashboard.council = council;
    }

    private static Council council;
    private Student student;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionChangePassword;
    private javax.swing.JButton actionSearch;
    private javax.swing.JButton actionUpdate;
    private javax.swing.JPanel actionsPane;
    private javax.swing.JTextArea announcement;
    private javax.swing.JPanel announcementPane;
    private javax.swing.JScrollPane announcementScroller;
    private javax.swing.JButton borrowEquipment;
    private javax.swing.JTextField confirmPassword;
    private javax.swing.JTextField contactNumber;
    private javax.swing.JPanel coucilDetailPane;
    private javax.swing.JPanel dashboardTab;
    private javax.swing.JComboBox department;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JTextField email;
    private javax.swing.JPanel events;
    private javax.swing.JComboBox eventsSelection;
    private javax.swing.JPanel filterEventPane;
    private javax.swing.JTextField firstName;
    private javax.swing.JButton fundButton;
    private javax.swing.JComboBox gender;
    private javax.swing.JTextField idNumber;
    private javax.swing.JTextField infoDepartment;
    private javax.swing.JTextField infoName;
    private javax.swing.JTextField infoYearLevel;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField keyword;
    private javax.swing.JLabel labelConfirmPassword;
    private javax.swing.JLabel labelContactNumber;
    private javax.swing.JLabel labelDepartment;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEvent;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelIDNumber;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNewPassword;
    private javax.swing.JLabel labelOldPassword;
    private javax.swing.JLabel labelSearchKeyword;
    private javax.swing.JLabel labelShirtSize;
    private javax.swing.JLabel labelYear;
    private javax.swing.JLabel labelYearLevel;
    private javax.swing.JTextField lastName;
    private javax.swing.JButton logout;
    private javax.swing.JTextField newPassword;
    private javax.swing.JTextField oldPassword;
    private javax.swing.JPanel passwordsPane;
    private javax.swing.JButton registerNewCouncil;
    private javax.swing.JButton registerNewStudent;
    private javax.swing.JPanel searchStudentPanel;
    private javax.swing.JTextField shirtSize;
    private javax.swing.JMenu showLog;
    private javax.swing.JLabel spacer;
    private javax.swing.JPanel studentDetailsPane;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JMenuBar tools;
    private javax.swing.JButton viewEquipment;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}
